dev-docs/COMMANDS
dev-docs/DEVELOPERS.md
dev-docs/INSTALL.md
dev-docs/NEW-COMMANDS.md
dev-docs/PARSING.md
dev-docs/TODO.md

Hi, while going through the docs, I have fixed some minor typos.

fix minor typos

---

libs/PictureGraphics.c

This pull-request is about this issue #42

Do we need to check the value returned from FCreateFImage?

---

doc/fvwm/expansion.xml

Document $[monitor.page]

---

.github/workflows/ccpp.yml

This adds a new github action script to use GH's native CI, rather than travis-ci.

Create github action script

---

.github/workflows/ccpp.yml

These clutter up IRC too much.

gh workflows: remove sending PR messages

---

fvwm/add_window.c
fvwm/borders.c
fvwm/events.c
fvwm/expand.c
fvwm/virtual.c

GCC: fix warnings

---

fvwm/Makefile.am
libs/Makefile.am

Some files are missing in a resulting tarbal created by ```make dist``` command

Fix 'dist' target

---

doc/fvwm/options.xml
libs/log.c

- logging: mention -v and rename log file
- verbose: actually open log file

Rename log filfe

---

contrib/randr-tool/randr.c
fvwm/icons.c
libs/FScreen.c

Replace calloc by fxcalloc

---

dev-docs/DEVELOPERS.md

Be explicit about fvwm3, and mention how to use topic branches for PRs.

Additional FVWM3 references

---

bin/fvwm-menu-desktop.in

catch when _do_check() fails

---

modules/FvwmMFL/FvwmMFL.c

When a client connects, send through connection_profile, detailing
version information from Fvwm3.
This will be useful to allow clients to determine what to do with
different Fvwm versions over time.

FvwmMFL: add connection_profile

---

doc/commands/EwmhBaseStruts.xml

Mention that EwmhBaseStruts is screen/RandR aware.
Fixes #208

doc: EwmhBaseStruts mention screen attribute

---

libs/safemalloc.h

Some BSDs require this header.

safemalloc: add stddef.h

---

doc/fvwm/expansion.xml
fvwm/expand.c
fvwm/move_resize.c

This adds expansion parameters to determine which page a window is on.
Fixes #255

Expansion: add $[w.pagex] $[w.pagey]

---

fvwm/virtual.c

desk_get_fw_count: remove debug

---

doc/bin/FvwmPrompt.adoc

Add a man page for the FvwmPrompt command.

FvwmPrompt: add basic manpage

---

configure.ac
fvwm/builtins.h
modules/FvwmMFL/FvwmMFL.c

* Ensure libbson is referenced properly
* Use the libbson libs arguments from pkg-config.

OpenBSD/SunOS: fix compilation problems

---

fvwm/virtual.c

HandlePaging: ignore bounds check

---

.github/workflows/ccpp.yml

CI: Tweak CHANGELOG generator

---

libs/modifiers.h

Add missing header for modifiers.

FreeBSD: include fvwm_x11.h for modifiers

---

.github/workflows/issues.yml

Define some actions to notify IRC when issues status' change.

CI: add issues script

---

modules/FvwmMFL/FvwmMFL.c

FvwmMFL: only allow one instance to run
Because FvwmMFL is intended to serve multiple clients over a single UDS,
don't permit more than one instance to load at any one time.  This
reduces socket-clobbering problems.
Noticed by Dominique Michel on IRC.
Fixes #348

FvwmMFL: only allow one instance to run

---

dev-docs/DEVELOPERS.md

Tweak the development documentation to reflect the current status of how
things are built.

dev-doc: slight improvements

---

fvwm/events.c
fvwm/virtual.c

Default to checking unamp events at the appropriate edgethickness.

EdgeCommands: tweak map logic

---

.github/issue_label_bot.yaml
.github/workflows/ccpp.yml

Change the labels that issue bot is aware of, to match those labels
which fvwm3 now defines.

issue-bot: update labels

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md

Include templates for PRs and issues to get better information upfront,
and for users/developers to know what to expect.

Github: add templates for PRs/issues

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature.md

Mention that fvwm3 has builtin logging and how to enable it.

CI: issue template: mention logging

---

fvwm/fvwm3.c

Since commit 841524a34b5741ae6024e11cf64fc8dcb39057cb, system.fvwm2rc is not found at startup.

Fix system.fvwm2rc not found

---

doc/modules/FvwmIconMan.adoc
fvwm/conditional.c
fvwm/ewmh_conf.c
fvwm/expand.c
fvwm/module_interface.c
fvwm/move_resize.c
fvwm/placement.c
fvwm/style.c
fvwm/virtual.c
libs/FScreen.c
libs/FScreen.h
libs/vpacket.h
modules/FvwmIconMan/FvwmIconMan.h
modules/FvwmIconMan/fvwm.c
modules/FvwmIconMan/readconfig.c
modules/FvwmIconMan/winlist.c
modules/FvwmIconMan/x.c

- API: introduce API to resolve symbolic monitors
- vpacket: augment CONFIGARGS with monitor_name
- FvwmIconMan: track a window's monitor
- FvwmIconMan: handle 'resoltuion screen <x>'

FvwmIconMan: handle resolutions for per-monitor

---

fvwm/virtual.c

When initialising panframes, in global mode, only surround the
outer-edges with panframes.  This should stop odd page-switching
behaviour when previously, panframes were left per-monitor, despite a
DesktopConfiguration of 'global'.
Fixes #398

PanFrames: restore global panframe behaviour

---

configure.ac
libs/fvwm_x11.h

move x11 headers out of config.h.

move x11 headers out of config.h

---

libs/Fft.c

Initialise the LocaleCharset when the font structure is also setup.

LocaleCharset: initialise with font

---

doc/fvwm3/fvwm3.adoc
fvwm/conditional.c

This adds conditions for `HasTitle` and `HasBorders`.

conditionals: add HasBorders/HasTitle

---

libs/Graphics.c

Some pixels are off with 3d buttons. I believe when drawing buttons a = 1 so we are missing out a pixel by adding `l`.

fix with some pixels off for 3d buttons

---

fvwm/add_window.c
fvwm/style.c
libs/FEvent.c
libs/Fft.c

fixed some heap corruption. 
Some of them can be triggered by start/restart fvwm.

fix uninitialized value and bad free

---

libs/Graphics.c

Gosh this is hard. Understanding `a is crucial to the code.

Fix the pixel overflow problem and clean up the math.

---

dev-docs/TODO.md

* Marked some items as completed
* Removed a few which won't ever get done.

TODO: tidy up

---

fvwm/add_window.c
fvwm/builtins.c
fvwm/events.c
fvwm/ewmh_events.c
fvwm/focus.c
fvwm/geometry.c
fvwm/menus.c
fvwm/misc.c
fvwm/move_resize.c
fvwm/placement.c
fvwm/session.c
fvwm/virtual.c

This removes variables which are no longer used (due to recent API
changes with MyDisplay{Width,Height}

Remove unused variables

---

libs/Fft.c

fix shadow position bug

---

fvwm/focus.c
fvwm/fvwm3.c
fvwm/misc.c
libs/Fft.c
libs/FftInterface.h
libs/Flocale.h
libs/FlocaleCharset.c
modules/FvwmForm/FvwmForm.c
modules/FvwmForm/ReadXServer.c
modules/FvwmPager/FvwmPager.c
modules/FvwmPager/FvwmPager.h

* Make all comments use /* ... */ and not '//';
* Remove commented out code where no longer useful

style: few cleanps

---

.github/workflows/ccpp.yml
.github/workflows/issues.yml

- Notifier: switch IRC actions
- IRC: more notifier changes

IRC Notifier: Switch Github Actions

---

default-config/config

Update the manpage menu to open the manpage for fvwm3 and remove some entries for retired modules.

Update manpages in default-config

---

.gitignore

Just some additions to .gitignore for some more generated files that were not being ignored.

Add some more generated files to .gitignore.

---

.github/workflows/ccpp.yml
.github/workflows/issues.yml

Avoid potential clashes with usernames.

IRC: update nicknames

---

configure.ac
po/Makefile.am

Move locale directory from $PREFIX/share/locale to $FVWM_DATADIR/locale to make installing along side fvwm2 easier.

Move locale directory to $FVWM_DATADIR

---

doc/bin/FvwmCommand.adoc

This adds documentation for FvwmCommand.
Fixes #393

manpage: add FvwmCommand

---

default-config/config

Adds DesktopConfigure to config and a short explanation of the available modes.

Add DesktopConfigure to config

---

configure.ac

- Style guide followed (try and match the surrounding code where possible)
- All tests are passing:  although this is automatic, Codacy will often
highlight additional considerations which will need to be addressed before
the PR can be merged.
```
Fixes #XXX
```
at the end of your commit message, where `XXX` should be …

Working on 1.0.4

---

Makefile.am

This includes the CHANGELOG.md file in the release tarball.

build: add CHANGELOG.md to dist

---

default-config/config

This PR implements two changes:
1. Fixes a few spelling/typographical errors.
2. Simplifies ToggleTitle function.

Configuration tweaks

---

dev-docs/DEVELOPERS.md

The linux kernel coding style doc moved.

Fix broken link.

---

fvwm/placement.c

placement: remove conditional

---

doc/fvwm3/fvwm3.adoc
fvwm/expand.c

This adds a few more variables which exposes more internal state for use
in functions and modules.

expand: add desk, pagex, pagey variables

---

modules/FvwmPager/x_pager.c

This function now correctly computes the size and location of the current viewport. No need to include all the previous complications due to the sizes are already accurately stored in desk_w and desk_h. This also makes it so MovePage() can use this function as well.
This also fixes issues with showing the view port in the correct location when resizing the FvwmPager window.

Fix set_vp_size_and_loc() for FvwmPager.

---

default-config/config

Update the colorset for greyed menus to have grey text so it is noticeably distinct from other items.

Make default-config greyed colorset grey.

---

doc/fvwm3/fvwm3.adoc

Fix typo in manual page.

---

acinclude.m4
bin/fvwm-menu-directory.in
configure.ac
doc/fvwm3/fvwm3.adoc
libs/defaults.h
modules/FvwmIconMan/xmanager.c

This PR includes the following patches from Debian:
* FvwmIconMan-fix-size-hints-warnings-2.patch
* enable-more-mouse-buttons.patch
* manpage-ClickTime.patch
* menu-directory.patch
* pkgconfig.patch

Patches from Debian

---

fvwm/stack.c
fvwm/windowlist.c

* Fix typos in comments. No code changes.

Fix typos.

---

fvwm/virtual.c

Remove some less-useful debugging.

debug: tidy-up

---

.github/workflows/release.yml

* Change the release branch name to: release/1.x.y
* Make sure the origin branch is set to upstream before pushing it.

github: release: tweak automation script

---

fvwm/virtual.c

When switching between desks, and trying to handle the state between a
global monitor and one in shared mode, don't try and co-opt the two sets
of logic.
Instead, split them up, such that global mode is treated separately from
shared.  This also means the assignment of the EWMH desk is put into its
own function, reducing some duplication.
Fixes #721

gotodesk: simplify logic for shared/global

---

fvwm/borders.c

Don't clobber the border relief if MWMBorder is used.

MWMBorder: fix calculation

---

.github/release.yml
.github/workflows/release.yml
mkrelease.sh

This automates the process of putting in place a release for fvwm.
This is enacted by running the manual workflow and inputting the next
release.  As such, that will then generate a PR with all the relevant
information.

workflow: automate release process

---

configure.ac

ver: back to 1.0.7

---

fvwm/borders.c

Revert MWM borders line width in border_fetch_mwm_layout

Revert MWM borders line width in border_fetch_mwm_layout

---

configure.ac

configure: support newer golang versions

---

fvwm/ewmh.c
fvwm/virtual.c
libs/FScreen.c

Complete and utter bullshit, but this might just help with multi-monitor
setups.
Fixes #779

EWMH: Update SetWorkArea() to use global w/h

---

modules/FvwmScript/Widgets/CheckBox.c

Adjust checkbox areas for font-widths.  Noticed by Jorg Blodorn.

FvwmScript: fix rendering of checkboxes

---

fvwm/fvwm3.c

Fix a typo in fvwm3 -h

---

Makefile.am
contrib/xsession/fvwm3.desktop.in

Add Keywords and Icon to fvwm3.desktop file. In addition adjust Comment to not match Keywords exactly.

Add Keywords and Icon to fvwm3.desktop file.

---

po/FvwmScript.zh_TW.po
po/fvwm.zh_TW.po

Update chinese traditional translate.

Update Chinese translate

---

configure.ac

build: set next version

---

modules/FvwmPager/x_pager.c

The logic for testing for this got lost in a previous commit. Adding it back. This fixes #1000.

FvwmPager Bugfix: Fix UseSkipList

---

bin/FvwmCommand.in

Needed since commit da4387b.
Fixes #1034

FvwmCommand: look for FVWMMFL_SOCKET_PATH

---

default-config/config

`Style * Lenience` makes some apps behave better, add this to the default config to help deal with such apps (java prgrams are a common example of such an app).

Add Style * Lenience to default config.

---

dev-docs/INSTALL.md
meson.build
meson.options

Noticed there were a few missing optional dependencies.

Make xkbcommon required in meson. 

---

dev-docs/INSTALL.md

Fix description for mandoc and htmldoc options in dev-docs/INSTALL.md

swapped mandoc and htmldoc options

---

bin/FvwmPrompt/FvwmPrompt.go

- **FvwmPrompt: don't blindly quit if "quit" given**
- **FvwmPrompt: fix syntax**

FvwmPrompt: honour "quit" as case-sensitive

---

fvwm/modconf.c
libs/log.c
libs/log.h
modules/FvwmBacker/FvwmBacker.c
modules/FvwmBacker/root_bits.c
modules/FvwmButtons/FvwmButtons.c
modules/FvwmButtons/button.c
modules/FvwmButtons/draw.c
modules/FvwmButtons/output.c
modules/FvwmButtons/parse.c
modules/FvwmConsole/FvwmConsole.c
modules/FvwmConsole/FvwmConsoleC.c
modules/FvwmIconMan/FvwmIconMan.c
modules/FvwmIconMan/debug.c
modules/FvwmIconMan/readconfig.c
modules/FvwmIconMan/x.c
modules/FvwmIconMan/xmanager.c
modules/FvwmIdent/FvwmIdent.c

- **log: expose ability query/set fd**
- **modules: convert to use fvwm_debug**

Allow modules to use fvwm_debug

---

bin/fvwm-convert-2.6.in

Noticed by AlaricToo on #fvwm IRC.

fvwm-convert-2.6: fix syntax error

---

.github/workflows/ccpp.yml

Let this be handled by issues.yml

CI: ccpp: remove notification section
